server:
  port: 5006

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/jwttestdb
    password: DTU@1657
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379